/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useAuthStore: typeof import('./src/stores/auth').useAuthStore
  const useLoadingBatchStore: typeof import('./src/stores/loadingBatch').useLoadingBatchStore
  const useUiStore: typeof import('./src/stores/ui').useUiStore
}
